{{- if and (eq .Values.type "Rollout") .Values.rollout.strategy.blueGreen }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.strategy.blueGreen.previewService | default (printf "%s-preview" (include "mark.fullname" .)) }}
  labels:
    {{- include "mark.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mark.selectorLabels" . | nindent 4 }}
{{- end }}
